version: 2
enable-beta-ecosystems: true
updates:
  - package-ecosystem: cargo
    directory: native/
    schedule:
      interval: weekly
  - package-ecosystem: pub
    directory: ./
    schedule:
      interval: weekly
